version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: smart-clinic-mysql-dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: smart_clinic_db
      MYSQL_USER: clinic_user
      MYSQL_PASSWORD: clinic_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_dev_data:/var/lib/mysql
    networks:
      - smart-clinic-dev-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 30s

  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: smart-clinic-mongodb-dev
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: smart_clinic_mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_dev_data:/data/db
    networks:
      - smart-clinic-dev-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 30s

  # Smart Clinic Management System Application (Development Mode)
  smart-clinic-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smart-clinic-app-dev
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      
      # MySQL Configuration
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: smart_clinic_db
      MYSQL_USER: clinic_user
      MYSQL_PASSWORD: clinic_password
      
      # MongoDB Configuration
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DATABASE: smart_clinic_mongo_db
      
      # JWT Configuration
      JWT_SECRET: bXlTZWNyZXRLZXlGb3JTbWFydENsaW5pY01hbmFnZW1lbnRTeXN0ZW0yMDI0
      JWT_EXPIRATION: 86400
      JWT_REFRESH_EXPIRATION: 604800
      
      # Logging Configuration (More verbose for development)
      LOG_LEVEL: DEBUG
      ROOT_LOG_LEVEL: INFO
      
      # Java Options for development
      JAVA_OPTS: "-Xmx256m -Xms128m -XX:+UseG1GC"
      
    ports:
      - "8080:8080"
    volumes:
      - app_dev_logs:/app/logs
      - ./src:/app/src:ro  # Mount source code for development
    networks:
      - smart-clinic-dev-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      timeout: 30s
      retries: 5
      interval: 30s
      start_period: 60s

# Volumes for persistent data
volumes:
  mysql_dev_data:
    driver: local
  mongodb_dev_data:
    driver: local
  app_dev_logs:
    driver: local

# Networks
networks:
  smart-clinic-dev-network:
    driver: bridge