name: Nightly Security Scan

on:
  schedule:
    - cron: '0 2 * * *'  # Run at 2 AM UTC daily
  workflow_dispatch:  # Allow manual triggering

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  security-scan:
    name: Nightly Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run Trivy filesystem scan
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-fs-results.sarif'
        
    - name: Upload filesystem scan results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-fs-results.sarif'
        category: 'filesystem-scan'
        
    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Scan latest Docker image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        format: 'sarif'
        output: 'trivy-image-results.sarif'
        
    - name: Upload image scan results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-image-results.sarif'
        category: 'container-scan'
        
    - name: Create security report
      run: |
        echo "# Nightly Security Scan Report" > security-report.md
        echo "Scan Date: $(date)" >> security-report.md
        echo "" >> security-report.md
        echo "## Filesystem Scan" >> security-report.md
        trivy fs --format table . >> security-report.md
        echo "" >> security-report.md
        echo "## Container Scan" >> security-report.md
        trivy image --format table ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest >> security-report.md
        
    - name: Upload security report
      uses: actions/upload-artifact@v3
      with:
        name: security-report-${{ github.run_number }}
        path: security-report.md
        
    - name: Notify on high severity vulnerabilities
      if: failure()
      uses: 8398a7/action-slack@v3
      with:
        status: 'failure'
        channel: '#security'
        text: |
          🚨 High severity vulnerabilities detected in nightly security scan!
          Repository: ${{ github.repository }}
          Scan Date: $(date)
          Please review the security report artifacts.
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}